### PR TITLE
Added fish support for /me command

### PR DESCRIPTION
**Pull request by Groil**
This allows for encryption of /me command which was previously sent unencrypted to channels that had a fish key set.

### CODE REVIEW

**Comment by philicious** [comment]
cool :+1: I'll check and merge in some days when I'm back at home

**Comment by Groil** [comment]
Seems like my new sync ended up here as well. It removes the custom implementation of base64 and switched to the glib one as per the request from TingPing.

**Comment by philicious** [comment]
@Groil ye, everything you commit on your master branch will land in this PR aswell. Its fine tho. Cool thing theres another one working on this. I didnt have the time to work on it more and make it "please" the HexChat guys. 

If I merge your PR, the changes will also land in my PR https://github.com/hexchat/hexchat/pull/1440 against upstream repo. And fingers-crossed, we might finally get it merged in with joined forces :+1:

**Comment by Groil** [comment]
This is most likely all I can add at the moment. Hopefully i didn't screw anything up to much.

**Comment by philicious** [comment]
@Groil I didnt forget about your PR, its bookmarked. I just didnt get home yet where I could test etc the stuff

**Comment by philicious** [comment]
@Groil my PR (including your additions) got merged into Hexchat master !

**Pull request merged**
